# Generated by Django 5.2.1 on 2025-06-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vendor_alter_user_department_alter_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='contact_person_designation',
            field=models.CharField(blank=True, help_text='Designation of the contact person', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_person_name',
            field=models.CharField(blank=True, help_text='Name of the contact person', max_length=150, null=True),
        ),
    ]
