# Generated by Django 5.2.4 on 2025-08-20 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_vendor_contact_person_designation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name']},
        ),
    ]
