# Generated by Django 5.2.1 on 2025-06-18 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('agreement_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('expired', 'Expired')], default='ongoing', max_length=10)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('party_name', models.CharField(max_length=200)),
                ('reminder_time', models.DateField(editable=False)),
                ('attachment', models.FileField(upload_to='agreements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_users', models.ManyToManyField(related_name='assigned_agreements', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agreements', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_agreements', to='accounts.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
