# Generated by Django 5.2.1 on 2025-06-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='agreement_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
