# Generated by Django 5.2.1 on 2025-06-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_agreement_agreement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='agreement_reference',
            field=models.CharField(blank=True, help_text='Reference for this agreement (user input)', max_length=100, null=True),
        ),
    ]
