# Generated by Django 5.2.1 on 2025-06-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0003_agreement_agreement_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='reminder_time',
            field=models.DateField(),
        ),
    ]
