# Generated by Django 5.2.1 on 2025-06-29 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_vendor_contact_person_designation_and_more'),
        ('agreements', '0004_alter_agreement_reminder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='agreement_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='agreement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='accounts.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='party_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='accounts.vendor', verbose_name='Vendor'),
        ),
    ]
