# Generated by Django 5.2.1 on 2025-06-30 11:37

import agreements.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_vendor_contact_person_designation_and_more'),
        ('agreements', '0005_alter_agreement_agreement_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Agreement', 'verbose_name_plural': 'Agreements'},
        ),
        migrations.AlterField(
            model_name='agreement',
            name='agreement_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='attachment',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=agreements.models.agreement_file_path),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='reminder_time',
            field=models.DateField(help_text='Date when reminders should be sent'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('expired', 'Expired'), ('draft', 'Draft'), ('terminated', 'Terminated')], default='draft', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='agreement',
            constraint=models.UniqueConstraint(condition=models.Q(('agreement_reference__isnull', False)), fields=('agreement_reference',), name='unique_agreement_reference'),
        ),
    ]
