# Generated by Django 5.2.1 on 2025-07-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0008_auto_20250630_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='agreement_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
