# Generated by Django 5.2.1 on 2025-08-12 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0009_agreement_original_filename_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='agreement',
        #     name='remarks',
        #     field=models.TextField(blank=True, null=True, verbose_name='Additional Remarks'),
        # ),
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('expired', 'Expired'), ('draft', 'Draft'), ('terminated', 'Terminated')], default='ongoing', max_length=15),
        ),
        migrations.CreateModel(
            name='AgreementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agreement_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agreement Type',
                'verbose_name_plural': 'Agreement Types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='agreement',
            name='agreement_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agreements.agreementtype', verbose_name='Type of Agreement'),
        ),
    ]
