# Generated by Django 5.2.5 on 2025-08-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0010_agreement_remarks_alter_agreement_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Remarks'),
        ),
    ]
